### ISSUE TITLE
Issue during building project

### ISSUE THREAD

**Issue by pratikacharya1234** [arpan404/joor#13]
![hgvkhchvjgcvb](https://github.com/arpan404/joor/assets/148206903/7875be73-1726-4ca2-92f0-af04ac9a83f5)
When building project in Windows, error occurs  while creating release folder.

**Comment by arpan404** [comment]
This is working fine in Mac and Linux. So, it's throwing error in Windows. Will fix it soon.

**Comment by arpan404** [comment]
Fixed in v0.1

**Comment by pratikacharya1234** [comment]
thanks for solving. I will start contributing and use joor for backend.
